AspNet.Demo/Models/ErrorViewModel.cs
using System;

namespace AspNet.Demo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNet.Demo/Models/TicketListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNet.Demo.Models
{
    public class TicketListViewModel
    {
        public int Id { get; set; }
        public string IssueDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

AspNet.Demo/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNet.Demo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            

            return View();
        }
    }

    public class MyPage : Microsoft.AspNetCore.Mvc.Razor.RazorPage
    {
        public override Task ExecuteAsync()
        {
            throw new NotImplementedException();
        }
    }
}

AspNet.Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNet.Demo.Models;
using Microsoft.VisualBasic.CompilerServices;
using AspNet.Demo.EF;

namespace AspNet.Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TestService _testSvc;
        //private readonly ITestService _testSvc;

        public HomeController(ILogger<HomeController> logger, TestService tst)  // , ITestService tst)
        {
            _logger = logger;
            _testSvc = tst;
        }
        
        public IActionResult Index()
        {
            ViewBag.Strings = _testSvc.GetData();
            ViewBag.Tickets = new List<Ticket>
            {
                new Ticket { Title = "Primo Ticket" },
                new Ticket { Title = "Secondo Ticket" },
                new Ticket { Title = "Terzo Ticket" },
            };

            return View();
        }

        public IActionResult UpdatePartial()
        {
            var tickets = new List<Ticket>
            {
                new Ticket { Title = "Primo Ticket **" },
                new Ticket { Title = "Secondo Ticket **" },
                new Ticket { Title = "Terzo Ticket **" },
            };

            return PartialView("_TicketList", tickets);
        }

        public IActionResult UpdateViewComponent()
        {
            return ViewComponent("Tickets");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNet.Demo/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNet.Demo.EF;
using AspNet.Demo.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspNet.Demo.Controllers
{
    public class TicketController : Controller
    {
        private TicketContext _ctx;

        public TicketController(TicketContext context)
        {
            _ctx = context;
        }

        // GET: Ticket
        public ActionResult Index()
        {
            ViewBag.DateLabel = "Today it's ";

            var results = _ctx
                .Tickets
                .Select(t => new TicketListViewModel
                {
                    Id = t.Id,
                    IssueDate = t.IssueDate.ToString("dd-MMM-yyyy"),
                    Description = t.Description,
                    Title = t.Title
                });

            return View(results);
        }

        // GET: Ticket/Details/5
        public ActionResult Details(int id)
        {
            var result = _ctx
               .Tickets.Find(id);

            return View(result);
        }

        // GET: Ticket/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ticket ticket)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add insert logic here
                    _ctx.Tickets.Add(ticket);
                    _ctx.SaveChanges();

                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ticket/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int id)
        {
            ViewBag.Layout = "~/Views/Shared/_Layout_due.cshtml";
            return View();
        }

        // POST: Ticket/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult IsStateValid(int stateId)
        {
            if (stateId > 0 && stateId <= 3)
                return Json(true);
            return Json("State ID must be between 1 and 3");
        }
    }
}

AspNet.Demo/ViewComponents/TicketsViewComponent.cs
using AspNet.Demo.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNet.Demo.ViewComponents
{
    public class TicketsViewComponent : ViewComponent
    {
        private TicketContext _ctx;
        public TicketsViewComponent(TicketContext context)
        {
            _ctx = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await GetTickets();

            return await Task.FromResult(
                (IViewComponentResult)View("Tickets", model)    
            );
        }

        private Task<List<Ticket>> GetTickets()
        {
            return _ctx.Tickets.ToListAsync();
        }
    }
}

AspNet.Demo/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet.Demo ADMIN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-warning" asp-area="" asp-controller="Home" asp-action="Index">AspNet.Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="User" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AspNet.Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/lib/moment/moment.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AspNet.Demo/Areas/Admin/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

AspNet.Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var title = "Tickets as Parameter";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        @{
            foreach (string item in ViewBag.Strings)
            {
                <p><i class="fas fa-exclamation-circle"></i>&nbsp;From TestSvc: @item</p>
            }
        }
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        @*<partial name="_TicketList" model="ViewBag.Tickets" />*@
        @*<div id="div1"></div>
        <button class="btn btn-primary" id="reload">Refresh</button>*@
        <vc:tickets></vc:tickets>
        <email mail-to="roberto.ajolfi@icubed.it">Roberto Ajolfi</email>

        @*<div email mail-to="roberto.ajolfi@icubed.it"></div>*@
    </div>

@section Scripts {
    @*<script>
        $(document).ready(function () {
            $('#reload').on('click', function () {
                alert('ci passo');
                $("#div1").load("/home/updatepartial");
            });
        });
    </script>*@
}

AspNet.Demo/Views/Shared/Components/SingleTicket/SingleTicket.cshtml
@model AspNet.Demo.Models.TicketListViewModel

<tr>
    <td>
        @Model.Id
    </td>
    <td>
        @Model.IssueDate
    </td>
    <td style="background-color: coral;">
        <a style="color: white;" asp-action="Details" asp-route-id="@Model.Id">@Model.Title</a>
    </td>
    <td>
        @Model.Description
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) ///
        @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
    </td>
</tr>

AspNet.Demo/Views/Shared/Components/Tickets/Tickets.cshtml
@model IEnumerable<AspNet.Demo.EF.Ticket>

<div class="col-md-12" style="text-align: left; padding-top:20px; padding-bottom: 20px; background-color: cadetblue;">
    <ul style="list-style-type: none;">
        @foreach (var ticket in Model)
        {
            <li>
                <span style="font-weight: bold; color: white;">@ticket.Title</span> - 
                <span style="text-decoration:dotted; font-style: italic;">@ticket.Description</span>
            </li>
        }
    </ul> 
</div> 

AspNet.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet.Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNet.Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AspNet.Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/lib/moment/moment.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AspNet.Demo/Views/Shared/_Layout_due.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet.Demo Layout2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNet.Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="Admin" asp-controller="User" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AspNet.Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/lib/moment/moment.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AspNet.Demo/Views/Shared/_TicketList.cshtml
@model IEnumerable<AspNet.Demo.EF.Ticket>

<div class="text-center main-div">
    <ul>
        @foreach (AspNet.Demo.EF.Ticket item in Model)
        {
            <li>@item.Title</li>
        }
    </ul>
</div>
        

AspNet.Demo/Views/Ticket/Create.cshtml
@model AspNet.Demo.EF.Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label"></label>
                <input asp-for="IssueDate" class="form-control" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriorityId" class="control-label"></label>
                <input asp-for="PriorityId" class="form-control" />
                <span asp-validation-for="PriorityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateId" class="control-label"></label>
                <input asp-for="StateId" class="form-control" />
                <span asp-validation-for="StateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNet.Demo/Views/Ticket/Delete.cshtml
@model AspNet.Demo.EF.Ticket

@{
    ViewData["Title"] = "Delete";
    Layout = ViewBag.Layout;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNet.Demo/Views/Ticket/Details.cshtml
@model AspNet.Demo.EF.Ticket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriorityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriorityId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StateId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StateId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AspNet.Demo/Views/Ticket/Index.cshtml
@model IEnumerable<AspNet.Demo.Models.TicketListViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IssueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>